name: Compile installer

on:
  schedule:
    - cron: '27 13 * * *'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PocketMine-MP version
        id: pmmp_version
        run: |
          VERSION=`curl -s https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/build_info.json | jq -r '.base_version'`
          echo "::set-output name=VERSION::${VERSION}"
          echo $VERSION > version

      - uses: actions/cache@v2
        id: cache
        with:
          path: version
          key: pmmp-${{ steps.pmmp_version.outputs.VERSION }}

      - name: Rewrite install.nsi
        if: steps.cache.outputs.cache-hit != 'true'
        run: sed -i 's/0.0.0/${{ steps.pmmp_version.outputs.VERSION }}/' install.nsi

      - name: Download files
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -JLOs "https://jenkins.pmmp.io/job/PHP-7.4-Aggregate/lastSuccessfulBuild/artifact/PHP-7.4-Windows-x64.zip" &
          curl -JLOs "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP.phar" &
          curl -JLOs "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/start.cmd" &
          wait
          unzip -q PHP-7.4-Windows-x64.zip

      - name: Create installer
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y nsis > /dev/null
          makensis install.nsi

      - name: Create Release
        if: steps.cache.outputs.cache-hit != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.pmmp_version.outputs.VERSION }}
          release_name: PocketMine-MP ${{ steps.pmmp_version.outputs.VERSION }}
          body: Release PocketMine-MP v${{ steps.pmmp_version.outputs.VERSION }}

      - name: Upload Release Asset
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PocketMine-MP-${{ steps.pmmp_version.outputs.VERSION }}.exe
          asset_name: PocketMine-MP-${{ steps.pmmp_version.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream
