name: Compile installer

on:
  schedule:
    - cron: '27 13 * * *'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download files
        run: |
          curl -JLOs "https://jenkins.pmmp.io/job/PHP-7.4-Aggregate/lastSuccessfulBuild/artifact/PHP-7.4-Windows-x64.zip" &
          curl -JLOs "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP.phar" &
          curl -JLOs "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/start.cmd" &
          wait
          unzip -q PHP-7.4-Windows-x64.zip
          ls -la

      - name: Create installer
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y nsis > /dev/null
          makensis install.nsi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          release_name: PocketMine-MP 1.0.0

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PocketMine-MP-1.0.0.exe
          asset_name: PocketMine-MP-1.0.0.exe
          asset_content_type: application/octet-stream
